### ISSUE TITLE
Update to support AWS provider 3

### ISSUE THREAD

**Issue by robvadai** [cloudposse/terraform-aws-elastic-beanstalk-application#25]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Terraform version 3 should be supported.

## Additional Context

Upgrading to AWS provider version 3 breaks this module.

Related to https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/issues/142

**Comment by vlatkoboshkoski-allocate** [comment]
Just use 0.11.0 and it will be fine. You can close this issue
